### ISSUE TITLE
BUG - Lighthouse - Exceptions from Cog Uk Id creation

### ISSUE THREAD

**Issue by andrewsparkes** [sanger/lighthouse#136]
**Describe the bug**
Exceptions being thrown during Baracoda COG UK id creation.

**RT Ticket Number**
na

**To Reproduce**
Seems inconsistent. Several noticed in slack output over last few weeks.

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Additional context**
Example of Exception:
2020-10-12 13:07:04,232 lighthouse.blueprints.plates:47 ERROR Unable to create COG barcodes
Traceback (most recent call last):
 File "/code/lighthouse/blueprints/plates.py", line 45, in create_plate_from_barcode
   centre_prefix = add_cog_barcodes(samples)
 File "/code/lighthouse/helpers/plates.py", line 58, in add_cog_barcodes
   raise Exception("Unable to create COG barcodes")
Exception: Unable to create COG barcodes

**Comment by andrewsparkes** [comment]
Another of these today:

2020-10-15 10:49:28,531 lighthouse.blueprints.plates:47 ERROR Unable to create COG barcodes
Traceback (most recent call last):
 File "/code/lighthouse/blueprints/plates.py", line 45, in create_plate_from_barcode
   centre_prefix = add_cog_barcodes(samples)
 File "/code/lighthouse/helpers/plates.py", line 58, in add_cog_barcodes
   raise Exception("Unable to create COG barcodes")
Exception: Unable to create COG barcodes
